/**
 * Every icon in the game, named by what it *means* rather than where it lives.
 * Game modules reference these keys; only `registry.ts` knows what file (if any)
 * each one resolves to, so swapping an asset never touches a call site.
 *
 * This module deliberately imports nothing — `src/game/` can pull the type in
 * without dragging asset imports into pure logic.
 */
export type IconName =
  // --- POI categories ---
  | 'poi.supermarket'
  | 'poi.convenience'
  | 'poi.pharmacy'
  | 'poi.hospital'
  | 'poi.hardware'
  | 'poi.fuel'
  | 'poi.police'
  | 'poi.residential'
  | 'poi.foodcourt'
  | 'poi.mrt'
  | 'poi.industrial'
  | 'poi.school'
  | 'poi.waypoint'
  | 'poi.unknown'
  // --- factions ---
  | 'faction.muster'
  | 'faction.gotong'
  | 'faction.syndicate_88'
  | 'faction.sta'
  // --- survival meters ---
  | 'meter.health'
  | 'meter.hunger'
  | 'meter.thirst'
  | 'meter.energy'
  | 'meter.infection'
  // --- combat ---
  | 'stance.aggressive'
  | 'stance.guarded'
  | 'stance.precision'
  | 'stance.disengage'
  | 'combat.enemyHuman'
  | 'combat.enemyZombie'
  | 'combat.enemyAnimal'
  | 'combat.enemyMacaque'
  | 'combat.enemyOtter'
  | 'combat.enemyBoar'
  | 'combat.enemyMonitor'
  | 'combat.enemyDog'
  | 'combat.enemyCat'
  | 'combat.enemyRat'
  | 'combat.player'
  | 'combat.hostiles'
  | 'combat.encounter'
  // --- HDB block ---
  | 'hdb.unit'
  | 'hdb.stocked'
  | 'hdb.storeroom'
  | 'hdb.pantry'
  | 'hdb.cornerUnit'
  | 'hdb.stairwell'
  | 'hdb.service'
  | 'hdb.hazard'
  | 'hdb.nest'
  | 'hdb.den'
  | 'hdb.burning'
  | 'hdb.shelter'
  | 'hdb.notice'
  | 'hdb.unavailable'
  | 'hdb.sealedCollapsed'
  | 'hdb.sealedFlooded'
  | 'hdb.sealedWelded'
  | 'hdb.sealedBurnt'
  | 'hdb.collapse'
  | 'hdb.enterBlock'
  | 'hdb.scout'
  | 'hdb.breach'
  | 'hdb.trader'
  | 'hdb.doctor'
  | 'hdb.bunk'
  // --- MRT tunnel run ---
  | 'tunnel.platform'
  | 'tunnel.pack'
  | 'tunnel.scavenge'
  | 'tunnel.settlement'
  | 'tunnel.hazard'
  | 'tunnel.carriage'
  | 'tunnel.signal'
  | 'tunnel.checkpoint'
  | 'tunnel.unknown'
  // --- sleep quality (Rest indicator) ---
  | 'sleep.roof'
  | 'sleep.bed'
  // --- actions / chrome ---
  | 'action.sleep'
  | 'action.inventory'
  | 'action.logbook'
  | 'action.objectives'
  | 'action.stash'
  | 'action.travel'
  | 'action.search'
  | 'action.map'
  | 'action.status'
  | 'action.log'
  | 'action.evac'
  | 'action.mrt'
  | 'action.settings'
  | 'action.here'
  | 'action.target'
  | 'action.kills'
  | 'action.stats'
  | 'action.craft'
  | 'action.dayLogs'
  | 'action.close'
  // --- event choices, one per ChoiceKind ---
  | 'choice.check'
  | 'choice.pay'
  | 'choice.fight'
  | 'choice.leave'
  // --- run statistics ---
  | 'stat.value'
  // --- item inspect meta row (size / weight / value) ---
  // Drop assets at src/assets/icons/meta-size.png, meta-weight.png, meta-value.png
  | 'meta.size'
  | 'meta.weight'
  | 'meta.value'
  // --- weather / time ---
  | 'weather.clear'
  | 'weather.cloudy'
  | 'weather.rain'
  | 'weather.thunderstorm'
  | 'weather.haze'
  | 'weather.heat'
  | 'time.day'
  | 'time.dusk'
  | 'time.night'
  // --- character attributes ---
  | 'attr.strength'
  | 'attr.dexterity'
  | 'attr.endurance'
  | 'attr.perception'
  | 'attr.wits'
  // --- status flags ---
  | 'status.bleeding'
  | 'status.fractured'
  | 'status.crippled'
  | 'status.night'
  | 'status.blocked'
  | 'status.terrain'
  // --- equipment slots (shown when a slot is empty) ---
  | 'slot.head'
  | 'slot.body'
  | 'slot.hands'
  | 'slot.legs'
  | 'slot.feet'
  | 'slot.mainHand'
  | 'slot.offHand'
  | 'slot.bag'
  // --- item fallbacks, one per ItemEffect kind ---
  // Every item resolves to one of these unless its def names a specific key,
  // so a new item is never blank even before anyone draws it.
  | 'item.food'
  | 'item.water'
  | 'item.heal'
  | 'item.cure'
  | 'item.energy'
  | 'item.weaponMelee'
  | 'item.weaponRanged'
  | 'item.ammo'
  | 'item.fuel'
  | 'item.misc'
  // --- per-item art ---
  | 'item.canned_food'
  | 'item.rice_pack'
  | 'item.instant_noodles'
  | 'item.cooked_mee'
  | 'item.snacks'
  | 'item.hawker_meal'
  | 'item.bak_kwa'
  | 'item.army_ration'
  | 'item.milo_tin'
  | 'item.milo_dinosaur'
  | 'item.condensed_milk'
  | 'item.kaya_toast'
  | 'item.curry_puff'
  | 'item.nasi_lemak'
  | 'item.wild_boar_meat'
  | 'item.river_fish'
  | 'item.durian'
  | 'item.tiger_beer'
  | 'item.chin_chow'
  | 'item.yakult'
  | 'item.tiger_balm'
  | 'item.axe_oil'
  | 'item.po_chai'
  | 'item.splint'
  | 'item.n95_mask'
  | 'item.mosquito_coil'
  | 'item.wooden_stick'
  | 'item.meat_cleaver'
  | 'item.golf_club'
  | 'item.baseball_bat'
  | 'item.katana'
  | 'item.spear_knife'
  | 'item.spear_cleaver'
  | 'item.spear_parang'
  | 'item.changkol'
  | 'item.sbo_vest'
  | 'item.ez_link_card'
  | 'item.ez_link_knife'
  | 'item.red_packet'
  | 'item.joss_paper'
  | 'item.rain_tarp'
  | 'item.powerbank'
  | 'item.four_d_ticket'
  | 'item.water_bottle'
  | 'item.newater'
  | 'item.dirty_water'
  | 'item.purification_tabs'
  | 'item.cloth_rags'
  | 'item.glass_bottle'
  | 'item.spare_parts'
  | 'item.whetstone'
  | 'item.gun_oil'
  | 'item.soft_drink'
  | 'item.isotonic'
  | 'item.bandage'
  | 'item.painkillers'
  | 'item.medkit'
  | 'item.antibiotics'
  | 'item.antiseptic'
  | 'item.coffee'
  | 'item.kopi_c'
  | 'item.energy_drink'
  | 'item.kitchen_knife'
  | 'item.hammer'
  | 'item.crowbar'
  | 'item.lockpick'
  | 'item.fire_axe'
  | 'item.parang'
  | 'item.pistol'
  | 'item.shotgun'
  | 'item.ammo_box'
  | 'item.ammo_shell'
  | 'item.hard_hat'
  | 'item.riot_helmet'
  | 'item.motorcycle_helmet'
  | 'item.leather_jacket'
  | 'item.work_vest'
  | 'item.kevlar_vest'
  | 'item.army_uniform'
  | 'item.work_gloves'
  | 'item.cut_gloves'
  | 'item.grip_gloves'
  | 'item.tactical_gloves'
  | 'item.jeans'
  | 'item.work_trousers'
  | 'item.camo_pants'
  | 'item.riot_pads'
  | 'item.flip_flops'
  | 'item.sneakers'
  | 'item.hiking_boots'
  | 'item.combat_boots'
  | 'item.riot_shield'
  | 'item.torch'
  | 'item.fuel_can'
  | 'item.duct_tape'
  | 'item.batteries'
  | 'item.scrap_metal'
  | 'item.toolbox'
  | 'item.jewellery'
  | 'item.chicken_rice'
  | 'item.premium_bento'
  | 'item.bandung'
  | 'item.bike_helmet'
  | 'item.cricket_bat'
  | 'item.daypack'
  | 'item.hiking_pack'
  | 'item.military_rucksack'
  | 'item.school_bag'
  | 'item.box_cutter'
  | 'item.pipe_wrench'
  | 'item.police_baton'
  | 'item.welding_mask'
  | 'item.football_pads'
  | 'item.security_vest'
  // --- traits (create screen / chips; upload via Dev → Icons → trait) ---
  | 'trait.ns_combat'
  | 'trait.medic'
  | 'trait.hawker_cook'
  | 'trait.marathoner'
  | 'trait.karang_guni'
  | 'trait.tekong_legs'
  | 'trait.night_owl'
  | 'trait.thick_skin'
  | 'trait.kiasuism'
  | 'trait.kampong_spirit'
  | 'trait.ah_long_debt'
  | 'trait.water_baby'
  | 'trait.handyman'
  | 'trait.sixth_sense'
  | 'trait.pack_rat'
  | 'trait.mule'
  | 'trait.light_pockets'
  | 'trait.deep_sleeper'
  | 'trait.quiet_step'
  | 'trait.strong_back'
  | 'trait.iron_stomach'
  | 'trait.heat_hardened'
  | 'trait.silver_tongue'
  | 'trait.field_dressing'
  | 'trait.calm_hands'
  | 'trait.frugal'
  | 'trait.aircon_addict'
  | 'trait.picky_eater'
  | 'trait.glass_jaw'
  | 'trait.clumsy'
  | 'trait.hoarder'
  | 'trait.noisy'
  | 'trait.bad_knees'
  | 'trait.hemophilia'
  | 'trait.poor_sleep'
  | 'trait.squeamish'
  | 'trait.out_of_shape'
  | 'trait.weak_stomach'
  | 'trait.dehydrated'
  | 'trait.afraid_of_dark'
  | 'trait.thin_blood'
  | 'trait.short_fuse'
  | 'trait.heavy_sleeper'
  | 'trait.combat_veteran'
  | 'trait.trauma_medic'
  | 'trait.hyrox_champion'
  | 'trait.young_blood'
  | 'trait.estate_kitchen'
  | 'trait.estate_memory'
  | 'trait.operator'
  | 'trait.site_foreman'
  | 'trait.made_man'
  | 'trait.hypervigilant'
  | 'trait.shift_burnout'
  | 'trait.restlessness'
  | 'trait.never_outdoors'
  | 'trait.stall_voice'
  | 'trait.ruined_knees'
  | 'trait.desk_body'
  | 'trait.heavy_hands'
  | 'trait.warrant';

/**
 * What renders until a real asset is dropped in. Every key must have one, so the
 * UI is never blank mid-migration.
 */
export const EMOJI_FALLBACK: Record<IconName, string> = {
  'poi.supermarket': '🛒',
  'poi.convenience': '🏪',
  'poi.pharmacy': '💊',
  'poi.hospital': '🏥',
  'poi.hardware': '🔧',
  'poi.fuel': '⛽',
  'poi.police': '🚓',
  'poi.residential': '🏢',
  'poi.foodcourt': '🍜',
  'poi.mrt': '🚉',
  'poi.industrial': '🏭',
  'poi.school': '🏫',
  'poi.waypoint': '🛣️',
  'poi.unknown': '❓',

  'faction.muster': '🎖️',
  'faction.gotong': '🍜',
  'faction.syndicate_88': '🗡️',
  'faction.sta': '🚉',

  'meter.health': '❤️',
  'meter.hunger': '🍖',
  'meter.thirst': '💧',
  'meter.energy': '⚡',
  'meter.infection': '☣️',

  'stance.aggressive': '⚔️',
  'stance.guarded': '🛡️',
  'stance.precision': '🎯',
  'stance.disengage': '🏃',
  'combat.enemyHuman': '🧑‍🦲',
  'combat.enemyZombie': '🧟',
  'combat.enemyAnimal': '🐕',
  'combat.enemyMacaque': '🐒',
  'combat.enemyOtter': '🦦',
  'combat.enemyBoar': '🐗',
  'combat.enemyMonitor': '🦎',
  'combat.enemyDog': '🐕',
  'combat.enemyCat': '🐈',
  'combat.enemyRat': '🐀',
  'combat.player': '🧍',
  'combat.hostiles': '⚔️',
  'combat.encounter': '☣️',

  'hdb.unit': '🚪',
  'hdb.stocked': '📦',
  'hdb.storeroom': '🔧',
  'hdb.pantry': '🥫',
  'hdb.cornerUnit': '🪟',
  'hdb.stairwell': '🪜',
  'hdb.service': '🤝',
  'hdb.hazard': '☢️',
  'hdb.nest': '🧟',
  'hdb.den': '💀',
  'hdb.burning': '🔥',
  'hdb.shelter': '🛡️',
  'hdb.notice': '📋',
  'hdb.unavailable': '✕',
  'hdb.sealedCollapsed': '🧱',
  'hdb.sealedFlooded': '🌊',
  'hdb.sealedWelded': '🚧',
  'hdb.sealedBurnt': '🔥',
  'hdb.collapse': '💥',
  'hdb.enterBlock': '🏢',
  'hdb.scout': '👁️',
  'hdb.breach': '🔨',
  'hdb.trader': '🧺',
  'hdb.doctor': '🩺',
  'hdb.bunk': '🛏️',
  'tunnel.platform': '🚉',
  'tunnel.pack': '🧟',
  'tunnel.scavenge': '🧰',
  'tunnel.settlement': '🔦',
  'tunnel.hazard': '🌊',
  'tunnel.carriage': '🚃',
  'tunnel.signal': '📡',
  'tunnel.checkpoint': '🎫',
  'tunnel.unknown': '❔',

  'sleep.roof': '⌂',
  'sleep.bed': '🛏️',

  'action.sleep': '😴',
  'action.inventory': '🎒',
  'action.logbook': '📓',
  'action.objectives': '🎯',
  'action.stash': '📦',
  'action.travel': '🚶',
  'action.search': '🔦',
  'action.map': '🗺️',
  'action.status': '❤️',
  'action.log': '📜',
  'action.evac': '🚁',
  'action.mrt': '🚆',
  'action.settings': '⚙',
  'action.here': '📍',
  'action.target': '🎯',
  'action.kills': '💀',
  'action.stats': '📊',
  'action.craft': '🔧',
  'action.dayLogs': '🗓️',
  'action.close': '✕',

  'choice.check': '🎲',
  'choice.pay': '🤝',
  'choice.fight': '⚔️',
  'choice.leave': '🚶',

  'stat.value': '💰',

  'meta.size': '📐',
  'meta.weight': '⚖️',
  'meta.value': '💰',

  'weather.clear': '☀️',
  'weather.cloudy': '☁️',
  'weather.rain': '🌧️',
  'weather.thunderstorm': '⛈️',
  'weather.haze': '🌫️',
  'weather.heat': '🥵',
  'time.day': '☀️',
  'time.dusk': '🌆',
  'time.night': '🌙',

  'attr.strength': '💪',
  'attr.dexterity': '🤸',
  'attr.endurance': '🫀',
  'attr.perception': '👁️',
  'attr.wits': '🧠',

  'status.bleeding': '🩸',
  'status.fractured': '🦴',
  'status.crippled': '✕',
  'status.night': '🌙',
  'status.blocked': '⛔',
  'status.terrain': '🏙️',

  'slot.head': '🪖',
  'slot.body': '🦺',
  'slot.hands': '🧤',
  'slot.legs': '👖',
  'slot.feet': '👟',
  'slot.mainHand': '🗡️',
  'slot.offHand': '🛡️',
  'slot.bag': '🎒',

  'trait.ns_combat': '🪖',
  'trait.medic': '🩺',
  'trait.hawker_cook': '🍜',
  'trait.marathoner': '🏃',
  'trait.karang_guni': '🔦',
  'trait.tekong_legs': '🤸',
  'trait.night_owl': '🦉',
  'trait.thick_skin': '🦺',
  'trait.kiasuism': '🧠',
  'trait.kampong_spirit': '🤝',
  'trait.ah_long_debt': '🗡️',
  'trait.water_baby': '💧',
  'trait.handyman': '🔧',
  'trait.sixth_sense': '👁️',
  'trait.pack_rat': '🎒',
  'trait.mule': '⚖️',
  'trait.light_pockets': '🪶',
  'trait.deep_sleeper': '🛏️',
  'trait.quiet_step': '🚶',
  'trait.strong_back': '💪',
  'trait.iron_stomach': '🍖',
  'trait.heat_hardened': '🥵',
  'trait.silver_tongue': '🗣️',
  'trait.field_dressing': '🩹',
  'trait.calm_hands': '✋',
  'trait.frugal': '🪙',
  'trait.aircon_addict': '❄️',
  'trait.picky_eater': '🍽️',
  'trait.glass_jaw': '😵',
  'trait.clumsy': '🤕',
  'trait.hoarder': '📦',
  'trait.noisy': '📢',
  'trait.bad_knees': '🦵',
  'trait.hemophilia': '🩸',
  'trait.poor_sleep': '😪',
  'trait.squeamish': '🤢',
  'trait.out_of_shape': '😮‍💨',
  'trait.weak_stomach': '🤮',
  'trait.dehydrated': '🏜️',
  'trait.afraid_of_dark': '🌑',
  'trait.thin_blood': '☣️',
  'trait.short_fuse': '💥',
  'trait.heavy_sleeper': '💤',
  'trait.combat_veteran': '⚔️',
  'trait.trauma_medic': '🏥',
  'trait.hyrox_champion': '⚡',
  'trait.young_blood': '🏫',
  'trait.estate_kitchen': '🍛',
  'trait.estate_memory': '🗺️',
  'trait.operator': '💼',
  'trait.site_foreman': '🏗️',
  'trait.made_man': '🕴️',
  'trait.hypervigilant': '👀',
  'trait.shift_burnout': '🪫',
  'trait.restlessness': '😤',
  'trait.never_outdoors': '🏢',
  'trait.stall_voice': '📣',
  'trait.ruined_knees': '🦴',
  'trait.desk_body': '🖥️',
  'trait.heavy_hands': '👊',
  'trait.warrant': '📋',

  'item.food': '🥫',
  'item.water': '💧',
  'item.heal': '➕',
  'item.cure': '💊',
  'item.energy': '⚡',
  'item.weaponMelee': '🔪',
  'item.weaponRanged': '🔫',
  'item.ammo': '🧨',
  'item.fuel': '⛽',
  'item.misc': '📦',

  'item.canned_food': '🥫',
  'item.rice_pack': '🍚',
  'item.instant_noodles': '🍜',
  'item.cooked_mee': '🍜',
  'item.snacks': '🍪',
  'item.hawker_meal': '🍛',
  'item.bak_kwa': '🥓',
  'item.army_ration': '🎖️',
  'item.milo_tin': '🥤',
  'item.milo_dinosaur': '🥤',
  'item.condensed_milk': '🥛',
  'item.kaya_toast': '🍞',
  'item.curry_puff': '🥟',
  'item.nasi_lemak': '🍱',
  'item.wild_boar_meat': '🥩',
  'item.river_fish': '🐟',
  'item.durian': '🍈',
  'item.tiger_beer': '🍺',
  'item.chin_chow': '🧋',
  'item.yakult': '🍶',
  'item.tiger_balm': '🧴',
  'item.axe_oil': '💚',
  'item.po_chai': '💊',
  'item.splint': '🦴',
  'item.n95_mask': '😷',
  'item.mosquito_coil': '🌀',
  'item.wooden_stick': '🪵',
  'item.meat_cleaver': '🔪',
  'item.golf_club': '🏌️',
  'item.baseball_bat': '🏏',
  'item.katana': '⚔️',
  'item.spear_knife': '🔱',
  'item.spear_cleaver': '🔱',
  'item.spear_parang': '🔱',
  'item.changkol': '⛏️',
  'item.sbo_vest': '🎽',
  'item.ez_link_card': '💳',
  'item.ez_link_knife': '💳',
  'item.red_packet': '🧧',
  'item.joss_paper': '📄',
  'item.rain_tarp': '⛺',
  'item.powerbank': '🔌',
  'item.four_d_ticket': '🎫',
  'item.water_bottle': '💧',
  'item.newater': '🚰',
  'item.dirty_water': '🫗',
  'item.purification_tabs': '🧊',
  'item.cloth_rags': '🧻',
  'item.glass_bottle': '🍾',
  'item.spare_parts': '⚙️',
  'item.whetstone': '🪨',
  'item.gun_oil': '🛢️',
  'item.soft_drink': '🥤',
  'item.isotonic': '🧴',
  'item.bandage': '🩹',
  'item.painkillers': '💊',
  'item.medkit': '🧰',
  'item.antibiotics': '💉',
  'item.antiseptic': '🧪',
  'item.coffee': '☕',
  'item.kopi_c': '☕',
  'item.energy_drink': '🥫',
  'item.kitchen_knife': '🔪',
  'item.hammer': '🔨',
  'item.crowbar': '🪓',
  'item.lockpick': '🗝️',
  'item.fire_axe': '🪓',
  'item.parang': '🗡️',
  'item.pistol': '🔫',
  'item.shotgun': '🔫',
  'item.ammo_box': '🧨',
  'item.ammo_shell': '🔴',
  'item.hard_hat': '⛑️',
  'item.riot_helmet': '🪖',
  'item.motorcycle_helmet': '🏍️',
  'item.leather_jacket': '🧥',
  'item.work_vest': '🦺',
  'item.kevlar_vest': '🛡️',
  'item.army_uniform': '🎖️',
  'item.work_gloves': '🧤',
  'item.cut_gloves': '🧤',
  'item.grip_gloves': '🥊',
  'item.tactical_gloves': '🧤',
  'item.jeans': '👖',
  'item.work_trousers': '👖',
  'item.camo_pants': '🌲',
  'item.riot_pads': '🦵',
  'item.flip_flops': '🩴',
  'item.sneakers': '👟',
  'item.hiking_boots': '🥾',
  'item.combat_boots': '🥾',
  'item.riot_shield': '🛡️',
  'item.torch': '🔦',
  'item.fuel_can': '⛽',
  'item.duct_tape': '🩶',
  'item.batteries': '🔋',
  'item.scrap_metal': '🔩',
  'item.toolbox': '🧰',
  'item.jewellery': '💍',
  'item.chicken_rice': '📦',
  'item.premium_bento': '📦',
  'item.bandung': '📦',
  'item.bike_helmet': '📦',
  'item.cricket_bat': '📦',
  'item.daypack': '📦',
  'item.hiking_pack': '📦',
  'item.military_rucksack': '📦',
  'item.school_bag': '📦',
  'item.box_cutter': '📦',
  'item.pipe_wrench': '📦',
  'item.police_baton': '📦',
  'item.welding_mask': '📦',
  'item.football_pads': '📦',
  'item.security_vest': '📦',
};
